source 'https://rubygems.org'
gem 'rails', '~> 6.1.2' #this is rails version.

gem 'pg'   #database.

gem 'puma', '~> 3.0' # use in both development and production environments.
gem 'sass-rails', '~> 6' #Sass adapter for the Rails asset pipeline
gem 'uglifier', '>= 1.3.0'#Uglifier minifies JavaScript files by wrapping UglifyJS to be accessible in Ruby
#gem 'coffee-rails', '~> 4.1.0' #CoffeeScript adapter for the Rails asset pipeline.

gem 'jquery-rails' #This gem provides jQuery and
                #This gem provides jQuery and the jQuery-ujs driver for your Rails 4+ application.
                   #the jQuery-ujs driver for your Rails 4+ application.
gem 'turbolinks', '~> 5.x' #Turbolinks makes following links in your
#web application faster (use with Rails Asset Pipeline)
gem 'jbuilder', '~> 2.0' #Create JSON structures via a Builder-style DSL
 gem 'wdm', '>= 0.1.0'
gem 'binding_of_caller'


group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console' #A debugging tool for your Ruby on Rails applications.
  gem 'listen', '~> 3.0.5' #to file modifications and notifies you about the changes.
  gem 'spring'#pring is a Rails application preloader.
  #It speeds up development by keeping your application running in the background
  #so you don't need to boot it every time you run a test, rake task or migration.
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'better_errors' #Provides a better error page for Rails and other Rack apps. Includes source code inspection, a live
  #REPL and local/instance variable inspection for all stack frames.
  gem 'rails_layout' #Generates Rails application layout files for various front-end frameworks.
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'bootstrap-sass' #bootstrap-sass is a Sass-powered version of Bootstrap 3,
#ready to drop right into your Sass powered applications.
gem 'simple_form' #Forms made easy!


gem 'faker' #The faker gem automatically generates data for you that you can enter into a database.
gem 'kaminari' #Kaminari is a paginating tool written in Ruby.Kaminari is a
#Scope & Engine based, clean, powerful, agnostic,
#customizable and sophisticated paginator for Rails 3+
