
default: &default
  adapter: postgresql
  encoding: unicode
  


  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pokemon_development
  username: ravi
  password: 123456



  
test:
  <<: *default
  database: pokemon_test
  username: ravi
  password: 123456



production:
  <<: *default
  database: pokemon_production
  username: books
  password: <%= ENV['BOOKS_DATABASE_PASSWORD'] %>
