
default: &default
  adapter: postgresql
  encoding: unicode



  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fileupload_development
  username: rakhi
  password: 123456




test:
  <<: *default
  database: fileupload_test
  username: rakhi
  password: 123456



production:
  <<: *default
  database: fileupload_production
  username: books
  password: <%= ENV['BOOKS_DATABASE_PASSWORD'] %>
