source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'  #THIS IS RUBY VERSION.

gem 'rails', '~> 6.1.1' #rails version.
gem 'puma', '~> 5.0' #
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'carrierwave' #Upload files in your Ruby applications, map them to a range of ORMs, store them on different backends.
 gem 'devise' #login authentication.
gem 'bootsnap', '>= 1.4.4', require: false

group :production do
  gem 'pg', '~> 1.2', '>= 1.2.3'
end

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'sqlite3', '~> 1.4' #for database.
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'fog'   #interacts with different cloud services.
gem 'carrierwave_direct' #to upload files from Ruby applications.
gem 'sidekiq' #Sidekiq uses threads to handle many jobs at the same time in the same process.
